export type WeatherContextType = {
  temp?: number;
  country?: string;
  description?: string;
  icon?: string;
  name?: string;
  sunrise?: number;
  sunset?: number;
  temp_max?: number;
  temp_min?: number;
  dt?: number;
  city?: string;
  cityData?: object | any;
  loading?: boolean;
  setError?: string;
  speed?: number;
  humidity?: number;
  feels_like?: number;
  onAddCity: (city: string) => void;
};
